### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by anupamme** [scikit-quantum/scikit-quantum#5]
When I run the example solving xor with quantum_mlp I get this error

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Volumes/work/code/quantum/scikit-quantum/skquantum/machine_learning/quantum_multilayer_perceptron.py", line 96, in fit
    self.dev = qml.device('strawberryfields.fock', wires=self.n_features, cutoff_dim=10)
  File "/usr/local/lib/python3.7/site-packages/pennylane/__init__.py", line 207, in device
    "Device does not exist. Make sure the required plugin is installed."
pennylane._device.DeviceError: Device does not exist. Make sure the required plugin is installed.

I am new to penny lane. Do I need to install anything besides python package pennylane?

I am running it on OS X.

**Comment by MatKallada** [comment]
Thanks for the issue! Yeah, you need to install `[strawberryfields](https://pypi.org/project/StrawberryFields/)`and PennyLane's StrawBerryFields backend `[PennyLane-SF](https://pypi.org/project/PennyLane-SF/)`.

Let me know if it works for you.

**Comment by anupamme** [comment]
Installing tensorflow 1.3 solves the issue.
