### ISSUE TITLE
Implement a Generic Grover's Search for 3SAT

### ISSUE THREAD

**Issue by MatKallada** [scikit-quantum/scikit-quantum#8]
Given some arbitrary 3SAT problem, this function should generate a quantum circuit for solving the 3SAT in question.

    model = QuantumThreeSAT()
    model.fit(clauses)

**Comment by MatKallada** [comment]
@wpol18  We can skip this if it's useless and purely for documentation.

**Comment by wpol18** [comment]
I've generalized my Grover to solve for arbitrary k-SAT (provided you know the number of solutions in advance). Posting soon
